graphiql:
    mapping: /graphiql
    endpoint:
      graphql: /graphql
      subscriptions: /subscriptions
    subscriptions:
      timeout: 30000
      reconnect: false
    static:
      basePath: /
    enabled: true
    pageTitle: GraphiQL
    cdn:
        enabled: false
        version: 0.13.0
    props:
        resources:
            query: schema.graphqls
            defaultQuery: defaultQuery.graphql
        variables:
            editorTheme: "blue light"
    headers:
        Authorization: "Bearer <your-token>"